module tb;
  reg a, b;
  wire y;
  xor_gate uut(.a(a),.b(b),.y(y));
  initial begin
    a=0; b=0; #10;
    a=0; b=1; #10;
    a=1; b=0; #10;
    a=1; b=1; #10;
    $finish;
  end
  initial $monitor("a=%b b=%b y=%b",a,b,y);
  endmodule